= pulse library for Arduino =

This library allows to create non blocking delays and complex timings on Arduino board.
The pulse output can be any Arduino pin or simply a boolean variable which allows more logic combinaison for complex timings

For more information about this library please visit us at
https://github.com/plouc68000/pulse

== License ==

Copyright (C) 2022-2024 Plouc68000. All rights reserved.
Copyright (c) 2010 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
