= pulse library for Arduino =

This library allows to create non-blocking delays and complex timings on Arduino board, without having to deal yourself with the millis() function.
This library pulse handles the millis() mimic for you the propper way

The non-blocking pulse generated by the Library can act on any Arduino hardware pin ( with the class 'pin' ),
or to any boolean global variable ( with the class 'flag' ), this providing the flexibility to add more coded 
logic combinaison for the creation of complex timings.

HOW TO USE IT
-------------

#include "pulse.h"    // includes the classes 'pin' and 'flag'



1) pulse on a arduino pin    ( see example pulse_on_a_pin.ino )
-------------------------

// led22 = instantiation of pin, pulse is generated on pin LED2 with a duration of 5000 ms

pin led22(LED2,5000); 

The code for generating a non-blocking pulse on LED2 pin needs only the following  2 instructions

// 1.1 The pulse begins when setting LED2 pin to HIGH

digitalWrite(LED2,HIGH);

// 1.2 A simple Update() is needed in the loop() to provide the non-blocking pulse pulse duration 
//and turning LED2 pin to LOW when the Time is elapsed.

led22.Update();




2) pulse on a flag  ( see example pulse_on_a_boolean.ino )
------------------

The philosophy is the same as pulsing on a Arduino pin, just that the pulse is acting on a global boolean variable
rather then on a Arduino hardware pin. This gives the flexibility of combining the boolean variable with more 
conditional code for creating complex non-blocking timings without consuming a Arduino physical output pin.

// global boolean variable where pulse is acting on

bool flag1;

// flag11 = instanciation of flag acting on flag1 global variable with a ON time of 5000 ms

flag flag11(flag1,5000);

The code for generating a non-blocking pulse on the global variable flag1 needs only the following  2 instructions

// 2.1 The pulse begins when setting the boolean variable flag1 to true

flag1=true;

// 2.2 A simple Update() is needed in the loop() to monitor when the time is elapsed. In this case, 
// the update() function is returning a true condition. For generating a single pulse, the code has
// then to reset flag1 to false when update() is returning a true condition.
// If flag1 is not reset by the code, the pulse will occur continuously, which can be desired in some
// timing applications, see the example ( do_every_200ms.ino )  , scanning a push button every 200 ms for debouncing.

if (flag11.Update(flag1)==true) flag1=false;


See also the other examples of use of the pulse library with:

  -complex_timing_1.ino    pressing a push button generates a pulse of 1000 ms on a Arduino pin after a delay of 3000ms, 
                           all in non-blocking code

  -complex timing_2.ino    creating a blinker with 50 ms ON time and 200ms OFF time, all in non-blocking code
  
  -do_every_200ms.ino      scanning a push button every 200 ms for debouncing



== License ==

Copyright (C) 2022-2024 Plouc68000. All rights reserved.
Copyright (c) 2010 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
